networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: {}
  prometheus-data:
    driver: local

services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./cloudflare-ddns/config.json:/config.json
    network_mode: host

  traefik:
    image: traefik:latest
    container_name: traefik
    command: --api.insecure=true --providers.docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
    networks:
      - monitoring

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - monitoring
    labels:
      - traefik.http.routers.whoami.rule=Host(`ping.nicklai.dev`)

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    labels:
      - traefik.http.routers.grafana.rule=Host(`system.nicklai.dev`)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    expose:
      - 9090
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: host
    restart: unless-stopped
    command:
      - --path.rootfs=/host
      - --collector.systemd
      - --collector.processes
    volumes:
      - /:/host:ro,rslave
    expose:
      - 9100
    networks:
      - monitoring
